const CONTAINER_WIDTH = 800;

const CONTAINER_HEIGHT = 600;

const BIRD_HEIGHT = 50;

const BIRD_WIDTH = BIRD_HEIGHT;

const PIPE_WIDTH = 70;

const MIN_PIPE_HEIGHT = 20;

const INNITIAL_OBSTRACLES = 4;

const MIN_GAP = 150;

const MAP_WIDTH = CONTAINER_WIDTH * 10;

const COLORS = ['#2185C5', '#7ECEFD', '#FF7F66', '#123'];

const SPEED_INCREASE_INTERVAL = 5;

const GAP_DECREASE_INTERVAL = 5;

const ANIMATION_FRAME = 10;

const MAP_POSITION_CHANGE_BY = 0.06;
