export const HEADER_INFO = 'HEADER_INFO';

export const FETCH_STORY = 'FETCH_STORY';

export const FETCH_STORY_COMMENT = 'FETCH_STORY_COMMENT';

export const FETCH_TOP_STORIE_IDS = 'FETCH_TOP_STORIE_IDS';

export const FETCH_TOP_STORIE_LIST = 'FETCH_TOP_STORIE_LIST';
